apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encodé - remplacez par vos vraies valeurs
  platform-api-token: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmxiV0ZwYkNJNkltRmtiV2x1UUhSeWFXUjViV1V1WTI5dElpd2lYMmxrSWpvaU5UZzVPV1V3WVdOaE5qQXdOelF4TnpVMU5EUXpNemsKCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: # Sera généré automatiquement par GitLab CI
